### PR TITLE
Fix for Issue #98

### PR DESCRIPTION
**Pull request by danowar2k**
Find all options and not the optgroups. Optgroups are taken care of by the rest of the code it seems.

### CODE REVIEW

**Comment by crlcu** [comment]
Hi,

I think this is going to reintroduce the issue described on https://github.com/crlcu/multiselect/issues/58

**Comment by danowar2k** [comment]
Okay, I'll work on that in the near future...

**Comment by crlcu** [comment]
This seems more like a rewrite instead of a bugfix pull request.

**Comment by danowar2k** [comment]
Sorry, I completely forgot the pull request and didn't notice that commits on my master would appear on here (even if it works that way at work...). We're currently in the process of refactoring some of the code to better understand it and provide meaningful assistance for this plugin. This was not really intended to be a "overhaul pull request". Instead, we wanted to propose bugfixes as separate PRs when we're done with it. And maybe propose some of our refactorings...

**Comment by danowar2k** [comment]
Should I close the pull request and open some when we really have something to show for?

**Comment by crlcu** [comment]
Yep, I'll close this pull request and you can create another one when needed.

**Pull request closed without merging**
